version: '3.8'

services:
  frontend:
    build: ./frontend_01
    ports:
      - "1234:1234"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: ./backend_01
    ports:
      - "8000:8000"
