version: '3.8'

services:
  frontend:
    build: ./frontend_01
    ports:
      - "1234:1234"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://3.111.175.69:8000
  backend:
    build: ./backend_01
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://shrey:shrey@cluster0.bt3np.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

