version: '3.8'

services:
  frontend:
    build: ./frontend_01
    ports:
      - "1234:1234"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - backend_network

  backend:
    build: ./backend_01
    ports:
      - "8000:8000"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
